name: greetings2

on:
    push:
        branches:
            - main


jobs:
    hello_world:
        runs-on: ubuntu-22.04
        steps:
            - name: hello wolrd
              run: echo "hello world"
            - name: getting current date
              run: date
            - name: show directory
              run: ls -l
            - uses: actions/setup-node@v4
            - name: install dependencies
              run: npm install
            - name: Lint
              run: npm run eslint