name: greetings2

on:
    push:
        branches:
            - main


jobs:
    hello_world:
        runs-on: ubuntu-22.04
        steps:
            - name: hello wolrd
              run: echo "hello world"