name: deployment pipeline

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: see directory
          run: ls -l

        # - uses:actions/checkout@v4
        #     with:
        #         fetch-depth:0